# Generated by Django 5.1.3 on 2024-11-11 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedido', '0001_initial'),
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.reserva'),
        ),
    ]
